services:
  postgresdb:
    image: postgres:17.2-alpine3.21
    environment:
      - POSTGRES_USER=msvc_user
      - POSTGRES_PASSWORD=msvc_password 
      - POSTGRES_DB=msvc_db
    ports:
      - "5431:5432"
    volumes:
      - pg_db:/var/lib/postgresql/data
    restart: always
    networks:
      - msvc-auth-network
  
  auth_app:
    build: .
    environment:
      DB_CONN_STR: postgresql://msvc_user:msvc_password@postgresdb:5432/msvc_db?sslmode=disable
    ports:
      - 80:5000
    depends_on:
      - postgresdb 
    networks:
      - msvc-auth-network

volumes:
  pg_db:

networks:
  msvc-auth-network:

    